# 05-Configure.ps1
# Final configuration phase
# Version: 1.0.0

$scriptRoot = Split-Path $PSScriptRoot -Parent
Import-Module "$scriptRoot\core\Display.psd1" -Force -Global
Import-Module "$scriptRoot\core\Logger.psd1" -Force -Global

function Invoke-FinalConfiguration {
    param(
        [Parameter(Mandatory=$true)]
        [hashtable]$Config
    )

    Write-Section -Title "Final Configuration" -Icon "⚙️"
    Write-Log -Message "Starting final configuration" -Level "INFO"

    try {
        # Update server.properties
        Write-StatusBox -Title "Configuring server.properties" -Status "Processing" -Type "Progress"

        $serverPropsPath = Join-Path $Config.ServerPath "server.properties"
        if (Test-Path $serverPropsPath) {
            $props = Get-Content $serverPropsPath

            # Update settings
            $props = $props -replace "server-port=.*", "server-port=$($Config.ServerPort)"
            $props = $props -replace "max-players=.*", "max-players=$($Config.MaxPlayers)"
            $props = $props -replace "view-distance=.*", "view-distance=$($Config.ViewDistance)"
            $props = $props -replace "simulation-distance=.*", "simulation-distance=$($Config.SimulationDistance)"
            $props = $props -replace "gamemode=.*", "gamemode=$($Config.Gamemode)"
            $props = $props -replace "difficulty=.*", "difficulty=$($Config.Difficulty)"
            $props = $props -replace "online-mode=.*", "online-mode=$($Config.OnlineMode.ToString().ToLower())"
            $props = $props -replace "pvp=.*", "pvp=$($Config.PVP.ToString().ToLower())"
            $props = $props -replace "motd=.*", "motd=ClaudeNPC Server - AI Powered NPCs"

            $props | Set-Content $serverPropsPath
            Write-StatusBox -Title "server.properties" -Status "Updated" -Type "Success"
        }

        # Create HOPE NPC config
        Write-StatusBox -Title "Creating HOPE config" -Status "Processing" -Type "Progress"

        $pluginsPath = Join-Path $Config.ServerPath "plugins"
        $hopeConfigPath = Join-Path $pluginsPath "HOPE"

        if (-not (Test-Path $hopeConfigPath)) {
            New-Item -ItemType Directory -Path $hopeConfigPath -Force | Out-Null
        }

        # Get active provider config
        $provider = $Config.AIProvider
        $providerConfig = $Config.AIProviders[$provider]

        $hopeConfig = @"
# HOPE NPC Configuration
# Generated by HOPE Server Suite v2.1.0
# AI NPCs playing games to redefine reality

# Active AI Provider
active_provider: "$provider"

# AI Providers Configuration
providers:
  claude:
    name: "Anthropic Claude"
    api_key: "$($Config.AIProviders.claude.APIKey)"
    model: "$($Config.AIProviders.claude.Model)"
    base_url: "$($Config.AIProviders.claude.BaseURL)"
    max_tokens: $($Config.AIProviders.claude.MaxTokens)

  openai:
    name: "OpenAI GPT"
    api_key: "$($Config.AIProviders.openai.APIKey)"
    model: "$($Config.AIProviders.openai.Model)"
    base_url: "$($Config.AIProviders.openai.BaseURL)"
    max_tokens: $($Config.AIProviders.openai.MaxTokens)

  grok:
    name: "xAI Grok"
    api_key: "$($Config.AIProviders.grok.APIKey)"
    model: "$($Config.AIProviders.grok.Model)"
    base_url: "$($Config.AIProviders.grok.BaseURL)"
    max_tokens: $($Config.AIProviders.grok.MaxTokens)

  gemini:
    name: "Google Gemini"
    api_key: "$($Config.AIProviders.gemini.APIKey)"
    model: "$($Config.AIProviders.gemini.Model)"
    base_url: "$($Config.AIProviders.gemini.BaseURL)"
    max_tokens: $($Config.AIProviders.gemini.MaxTokens)

  sima:
    name: "DeepMind SIMA (Gaming AI)"
    api_key: "$($Config.AIProviders.sima.APIKey)"
    model: "$($Config.AIProviders.sima.Model)"
    base_url: "$($Config.AIProviders.sima.BaseURL)"
    max_tokens: $($Config.AIProviders.sima.MaxTokens)

  ollama:
    name: "Ollama (Local)"
    api_key: ""
    model: "$($Config.AIProviders.ollama.Model)"
    base_url: "$($Config.AIProviders.ollama.BaseURL)"
    max_tokens: $($Config.AIProviders.ollama.MaxTokens)

# Response Settings
response:
  temperature: 0.7
  timeout_seconds: 30
  retry_attempts: 3
  fallback_provider: "ollama"

# Conversation Settings
conversation:
  memory_length: 10
  timeout_minutes: 5
  cooldown_seconds: 3

# NPC Personalities
personalities:
  default:
    system_prompt: |
      You are a helpful NPC in a Minecraft server. You are friendly,
      concise, and roleplay as a character in this world. Keep responses
      brief (1-2 sentences). You can give directions, share lore, or
      engage in light conversation.

  merchant:
    system_prompt: |
      You are a merchant NPC. You're enthusiastic about trading,
      mention items you have for sale, and haggle playfully.

  guard:
    system_prompt: |
      You are a town guard. You're vigilant, speak formally,
      and warn players about dangers beyond the walls.

  sage:
    system_prompt: |
      You are a wise sage. You speak in riddles occasionally,
      share deep lore about the world, and guide heroes.
"@

        $hopeConfig | Set-Content (Join-Path $hopeConfigPath "config.yml")
        Write-StatusBox -Title "HOPE config" -Status "Created with $($providerConfig.Name)" -Type "Success"

        # Display final settings
        Write-Host ""
        Write-Host "  Server Configuration:" -ForegroundColor Cyan
        Write-Host "  ───────────────────────────────────────" -ForegroundColor DarkCyan
        Write-Host "  Server Path:     $($Config.ServerPath)" -ForegroundColor Gray
        Write-Host "  Server Port:     $($Config.ServerPort)" -ForegroundColor Gray
        Write-Host "  Max Players:     $($Config.MaxPlayers)" -ForegroundColor Gray
        Write-Host "  Gamemode:        $($Config.Gamemode)" -ForegroundColor Gray
        Write-Host "  Difficulty:      $($Config.Difficulty)" -ForegroundColor Gray
        Write-Host "  Memory:          $($Config.MemoryMin) - $($Config.MemoryMax)" -ForegroundColor Gray
        Write-Host "  Install Profile: $($Config.InstallProfile)" -ForegroundColor Gray
        Write-Host "  ───────────────────────────────────────" -ForegroundColor DarkCyan
        Write-Host ""

        Write-StatusBox -Title "Final Configuration" -Status "Complete" -Type "Success"
        Write-Log -Message "Final configuration complete" -Level "SUCCESS"

        return @{
            Success = $true
            Message = "Configuration complete"
            Data = @{ServerPath = $Config.ServerPath}
        }

    } catch {
        Write-StatusBox -Title "Configuration Failed" -Status $_.Exception.Message -Type "Error"
        Write-LogError -ErrorRecord $_
        return @{Success = $false; Message = $_.Exception.Message; Data = @{}}
    }
}
